// This file is generated from vendored official Tweede Kamer XSD files.
// Refresh with: cargo run -p opentk-sync --bin official-schema -- check

use super::{BaseAttribute, EntityType, Field, FieldKind, Occurs};

const ENTITEIT_TYPE_ATTRIBUTES: &[BaseAttribute] = &[
    BaseAttribute {
        name: "id",
        xsd_type: "idType",
        required: true,
    },
    BaseAttribute {
        name: "verwijderd",
        xsd_type: "xs:boolean",
        required: true,
    },
    BaseAttribute {
        name: "bijgewerkt",
        xsd_type: "xs:dateTime",
        required: true,
    },
];

const DOWNLOAD_ENTITEIT_TYPE_ATTRIBUTES: &[BaseAttribute] = &[
    BaseAttribute {
        name: "id",
        xsd_type: "idType",
        required: true,
    },
    BaseAttribute {
        name: "verwijderd",
        xsd_type: "xs:boolean",
        required: true,
    },
    BaseAttribute {
        name: "bijgewerkt",
        xsd_type: "xs:dateTime",
        required: true,
    },
    BaseAttribute {
        name: "contentType",
        xsd_type: "xs:string",
        required: false,
    },
    BaseAttribute {
        name: "contentLength",
        xsd_type: "xs:int",
        required: false,
    },
];

const ACTIVITEIT_FIELDS: &[Field] = &[
    Field {
        name: "voortouwcommissie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "voortgezetVanuit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "vervangenVanuit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 3,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 5,
    },
    Field {
        name: "onderwerp",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 6,
    },
    Field {
        name: "datumSoort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "datum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 8,
    },
    Field {
        name: "aanvangstijd",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 9,
    },
    Field {
        name: "eindtijd",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 10,
    },
    Field {
        name: "locatie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 11,
    },
    Field {
        name: "besloten",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "booleanType",
        order: 12,
    },
    Field {
        name: "status",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "stringType",
        order: 13,
    },
    Field {
        name: "vergaderjaar",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "vergaderjaarType",
        order: 14,
    },
    Field {
        name: "kamer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "stringType",
        order: 15,
    },
    Field {
        name: "noot",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 16,
    },
    Field {
        name: "vrsNummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "",
        order: 17,
    },
    Field {
        name: "sidVoortouw",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 18,
    },
    Field {
        name: "voortouwnaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 19,
    },
    Field {
        name: "voortouwafkorting",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 20,
    },
    Field {
        name: "voortouwkortenaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 21,
    },
    Field {
        name: "aanvraagdatum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 22,
    },
    Field {
        name: "datumVerzoekEersteVerlenging",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 23,
    },
    Field {
        name: "datumMededelingEersteVerlenging",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 24,
    },
    Field {
        name: "datumVerzoekTweedeVerlenging",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 25,
    },
    Field {
        name: "datumMededelingTweedeVerlenging",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 26,
    },
    Field {
        name: "vervaldatum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 27,
    },
];

const ACTIVITEIT: EntityType = EntityType {
    category: "Activiteit",
    xml_element: "activiteit",
    rust_name: "Activiteit",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: ACTIVITEIT_FIELDS,
};

const ACTIVITEITACTOR_FIELDS: &[Field] = &[
    Field {
        name: "activiteit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "fractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 3,
    },
    Field {
        name: "commissie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 4,
    },
    Field {
        name: "actorNaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "actorFractie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "relatie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "volgorde",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:unsignedInt",
        order: 8,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
    Field {
        name: "spreektijd",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 10,
    },
    Field {
        name: "sidActor",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 11,
    },
];

const ACTIVITEITACTOR: EntityType = EntityType {
    category: "ActiviteitActor",
    xml_element: "activiteitActor",
    rust_name: "ActiviteitActor",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: ACTIVITEITACTOR_FIELDS,
};

const AGENDAPUNT_FIELDS: &[Field] = &[
    Field {
        name: "activiteit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "onderwerp",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 3,
    },
    Field {
        name: "aanvangstijd",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateTimeType",
        order: 4,
    },
    Field {
        name: "eindtijd",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateTimeType",
        order: 5,
    },
    Field {
        name: "volgorde",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "unsignedIntType",
        order: 6,
    },
    Field {
        name: "rubriek",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 7,
    },
    Field {
        name: "noot",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 8,
    },
    Field {
        name: "status",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
];

const AGENDAPUNT: EntityType = EntityType {
    category: "Agendapunt",
    xml_element: "agendapunt",
    rust_name: "Agendapunt",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: AGENDAPUNT_FIELDS,
};

const BESLUIT_FIELDS: &[Field] = &[
    Field {
        name: "agendapunt",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "zaak",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "stemmingsSoort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "besluitSoort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "besluitTekst",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 5,
    },
    Field {
        name: "opmerking",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 6,
    },
    Field {
        name: "status",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "agendapuntZaakBesluitVolgorde",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 8,
    },
];

const BESLUIT: EntityType = EntityType {
    category: "Besluit",
    xml_element: "besluit",
    rust_name: "Besluit",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: BESLUIT_FIELDS,
};

const COMMISSIE_FIELDS: &[Field] = &[
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 1,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "afkorting",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "naamNl",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "naamEn",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "naamWebNl",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "naamWebEn",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "inhoudsopgave",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 8,
    },
    Field {
        name: "datumActief",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 9,
    },
    Field {
        name: "datumInactief",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 10,
    },
];

const COMMISSIE: EntityType = EntityType {
    category: "Commissie",
    xml_element: "commissie",
    rust_name: "Commissie",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: COMMISSIE_FIELDS,
};

const COMMISSIECONTACTINFORMATIE_FIELDS: &[Field] = &[
    Field {
        name: "commissie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "waarde",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 4,
    },
];

const COMMISSIECONTACTINFORMATIE: EntityType = EntityType {
    category: "CommissieContactinformatie",
    xml_element: "commissieContactinformatie",
    rust_name: "CommissieContactinformatie",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: COMMISSIECONTACTINFORMATIE_FIELDS,
};

const COMMISSIEZETEL_FIELDS: &[Field] = &[
    Field {
        name: "commissie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 2,
    },
];

const COMMISSIEZETEL: EntityType = EntityType {
    category: "CommissieZetel",
    xml_element: "commissieZetel",
    rust_name: "CommissieZetel",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: COMMISSIEZETEL_FIELDS,
};

const COMMISSIEZETELVASTPERSOON_FIELDS: &[Field] = &[
    Field {
        name: "commissieZetel",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 4,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 5,
    },
];

const COMMISSIEZETELVASTPERSOON: EntityType = EntityType {
    category: "CommissieZetelVastPersoon",
    xml_element: "commissieZetelVastPersoon",
    rust_name: "CommissieZetelVastPersoon",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: COMMISSIEZETELVASTPERSOON_FIELDS,
};

const COMMISSIEZETELVASTVACATURE_FIELDS: &[Field] = &[
    Field {
        name: "commissieZetel",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "fractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 4,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 5,
    },
];

const COMMISSIEZETELVASTVACATURE: EntityType = EntityType {
    category: "CommissieZetelVastVacature",
    xml_element: "commissieZetelVastVacature",
    rust_name: "CommissieZetelVastVacature",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: COMMISSIEZETELVASTVACATURE_FIELDS,
};

const COMMISSIEZETELVERVANGERPERSOON_FIELDS: &[Field] = &[
    Field {
        name: "commissieZetel",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 4,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 5,
    },
];

const COMMISSIEZETELVERVANGERPERSOON: EntityType = EntityType {
    category: "CommissieZetelVervangerPersoon",
    xml_element: "commissieZetelVervangerPersoon",
    rust_name: "CommissieZetelVervangerPersoon",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: COMMISSIEZETELVERVANGERPERSOON_FIELDS,
};

const COMMISSIEZETELVERVANGERVACATURE_FIELDS: &[Field] = &[
    Field {
        name: "commissieZetel",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "fractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 4,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 5,
    },
];

const COMMISSIEZETELVERVANGERVACATURE: EntityType = EntityType {
    category: "CommissieZetelVervangerVacature",
    xml_element: "commissieZetelVervangerVacature",
    rust_name: "CommissieZetelVervangerVacature",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: COMMISSIEZETELVERVANGERVACATURE_FIELDS,
};

const DOCUMENT_FIELDS: &[Field] = &[
    Field {
        name: "huidigeDocumentVersie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "bronDocument",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "activiteit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 3,
    },
    Field {
        name: "agendapunt",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 4,
    },
    Field {
        name: "zaak",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 5,
    },
    Field {
        name: "kamerstukdossier",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 6,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "documentNummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 8,
    },
    Field {
        name: "titel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
    Field {
        name: "onderwerp",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 10,
    },
    Field {
        name: "datum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "xs:dateTime",
        order: 11,
    },
    Field {
        name: "volgnummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "intType",
        order: 12,
    },
    Field {
        name: "vergaderjaar",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "vergaderjaarType",
        order: 13,
    },
    Field {
        name: "kamer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "intType",
        order: 14,
    },
    Field {
        name: "citeertitel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 15,
    },
    Field {
        name: "alias",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 16,
    },
    Field {
        name: "datumRegistratie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 17,
    },
    Field {
        name: "datumOntvangst",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 18,
    },
    Field {
        name: "aanhangselnummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 19,
    },
    Field {
        name: "kenmerkAfzender",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 20,
    },
    Field {
        name: "organisatie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 21,
    },
];

const DOCUMENT: EntityType = EntityType {
    category: "Document",
    xml_element: "document",
    rust_name: "Document",
    base: "downloadEntiteitType",
    base_attributes: DOWNLOAD_ENTITEIT_TYPE_ATTRIBUTES,
    fields: DOCUMENT_FIELDS,
};

const DOCUMENTACTOR_FIELDS: &[Field] = &[
    Field {
        name: "document",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "fractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 3,
    },
    Field {
        name: "commissie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 4,
    },
    Field {
        name: "actorNaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "actorFractie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "relatie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 8,
    },
    Field {
        name: "sidActor",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
];

const DOCUMENTACTOR: EntityType = EntityType {
    category: "DocumentActor",
    xml_element: "documentActor",
    rust_name: "DocumentActor",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: DOCUMENTACTOR_FIELDS,
};

const DOCUMENTVERSIE_FIELDS: &[Field] = &[
    Field {
        name: "document",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "status",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "versienummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "unsignedIntType",
        order: 3,
    },
    Field {
        name: "bestandsgrootte",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "unsignedIntType",
        order: 4,
    },
    Field {
        name: "extensie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "datum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateTimeType",
        order: 6,
    },
    Field {
        name: "externeidentifier",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
];

const DOCUMENTVERSIE: EntityType = EntityType {
    category: "DocumentVersie",
    xml_element: "documentVersie",
    rust_name: "DocumentVersie",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: DOCUMENTVERSIE_FIELDS,
};

const FRACTIE_FIELDS: &[Field] = &[
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 1,
    },
    Field {
        name: "afkorting",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "naamNl",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "naamEn",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "aantalZetels",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "unsignedIntType",
        order: 5,
    },
    Field {
        name: "aantalStemmen",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "unsignedIntType",
        order: 6,
    },
    Field {
        name: "datumActief",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 7,
    },
    Field {
        name: "datumInactief",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 8,
    },
];

const FRACTIE: EntityType = EntityType {
    category: "Fractie",
    xml_element: "fractie",
    rust_name: "Fractie",
    base: "downloadEntiteitType",
    base_attributes: DOWNLOAD_ENTITEIT_TYPE_ATTRIBUTES,
    fields: FRACTIE_FIELDS,
};

const FRACTIEZETEL_FIELDS: &[Field] = &[
    Field {
        name: "fractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 2,
    },
];

const FRACTIEZETEL: EntityType = EntityType {
    category: "FractieZetel",
    xml_element: "fractieZetel",
    rust_name: "FractieZetel",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: FRACTIEZETEL_FIELDS,
};

const FRACTIEZETELPERSOON_FIELDS: &[Field] = &[
    Field {
        name: "fractieZetel",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 4,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 5,
    },
];

const FRACTIEZETELPERSOON: EntityType = EntityType {
    category: "FractieZetelPersoon",
    xml_element: "fractieZetelPersoon",
    rust_name: "FractieZetelPersoon",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: FRACTIEZETELPERSOON_FIELDS,
};

const FRACTIEZETELVACATURE_FIELDS: &[Field] = &[
    Field {
        name: "fractieZetel",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 3,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 4,
    },
];

const FRACTIEZETELVACATURE: EntityType = EntityType {
    category: "FractieZetelVacature",
    xml_element: "fractieZetelVacature",
    rust_name: "FractieZetelVacature",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: FRACTIEZETELVACATURE_FIELDS,
};

const KAMERSTUKDOSSIER_FIELDS: &[Field] = &[
    Field {
        name: "titel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 1,
    },
    Field {
        name: "citeertitel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 2,
    },
    Field {
        name: "alias",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 3,
    },
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "xs:unsignedInt",
        order: 4,
    },
    Field {
        name: "toevoeging",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:string",
        order: 5,
    },
    Field {
        name: "hoogsteVolgnummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "xs:int",
        order: 6,
    },
    Field {
        name: "afgesloten",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "booleanType",
        order: 7,
    },
    Field {
        name: "kamer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 8,
    },
];

const KAMERSTUKDOSSIER: EntityType = EntityType {
    category: "Kamerstukdossier",
    xml_element: "kamerstukdossier",
    rust_name: "Kamerstukdossier",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: KAMERSTUKDOSSIER_FIELDS,
};

const PERSOON_FIELDS: &[Field] = &[
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 1,
    },
    Field {
        name: "titels",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "initialen",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "tussenvoegsel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "achternaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "voornamen",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "roepnaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "geslacht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "",
        order: 8,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
    Field {
        name: "geboortedatum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 10,
    },
    Field {
        name: "geboorteplaats",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 11,
    },
    Field {
        name: "geboorteland",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 12,
    },
    Field {
        name: "overlijdensdatum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 13,
    },
    Field {
        name: "overlijdensplaats",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 14,
    },
    Field {
        name: "woonplaats",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 15,
    },
    Field {
        name: "land",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 16,
    },
    Field {
        name: "fractielabel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 17,
    },
];

const PERSOON: EntityType = EntityType {
    category: "Persoon",
    xml_element: "persoon",
    rust_name: "Persoon",
    base: "downloadEntiteitType",
    base_attributes: DOWNLOAD_ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOON_FIELDS,
};

const PERSOONCONTACTINFORMATIE_FIELDS: &[Field] = &[
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "waarde",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 4,
    },
];

const PERSOONCONTACTINFORMATIE: EntityType = EntityType {
    category: "PersoonContactinformatie",
    xml_element: "persoonContactinformatie",
    rust_name: "PersoonContactinformatie",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOONCONTACTINFORMATIE_FIELDS,
};

const PERSOONGESCHENK_FIELDS: &[Field] = &[
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "omschrijving",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "datum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateType",
        order: 3,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 4,
    },
];

const PERSOONGESCHENK: EntityType = EntityType {
    category: "PersoonGeschenk",
    xml_element: "persoonGeschenk",
    rust_name: "PersoonGeschenk",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOONGESCHENK_FIELDS,
};

const PERSOONLOOPBAAN_FIELDS: &[Field] = &[
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "werkgever",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "omschrijvingNl",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "omschrijvingEn",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "plaats",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "datumType",
        order: 7,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "datumType",
        order: 8,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 9,
    },
];

const PERSOONLOOPBAAN: EntityType = EntityType {
    category: "PersoonLoopbaan",
    xml_element: "persoonLoopbaan",
    rust_name: "PersoonLoopbaan",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOONLOOPBAAN_FIELDS,
};

const PERSOONNEVENFUNCTIE_FIELDS: &[Field] = &[
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "omschrijving",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "isActief",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "booleanType",
        order: 3,
    },
    Field {
        name: "periode",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "",
        order: 4,
    },
    Field {
        name: "vergoeding",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "",
        order: 5,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 6,
    },
];

const PERSOONNEVENFUNCTIE: EntityType = EntityType {
    category: "PersoonNevenfunctie",
    xml_element: "persoonNevenfunctie",
    rust_name: "PersoonNevenfunctie",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOONNEVENFUNCTIE_FIELDS,
};

const PERSOONNEVENFUNCTIEINKOMSTEN_FIELDS: &[Field] = &[
    Field {
        name: "persoonNevenfunctie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "jaar",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "bedragSoort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "bedragVoorvoegsel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "bedragValuta",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "bedrag",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:decimal",
        order: 6,
    },
    Field {
        name: "bedragAchtervoegsel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "frequentie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 8,
    },
    Field {
        name: "frequentieBeschrijving",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
    Field {
        name: "opmerking",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 10,
    },
];

const PERSOONNEVENFUNCTIEINKOMSTEN: EntityType = EntityType {
    category: "PersoonNevenfunctieInkomsten",
    xml_element: "persoonNevenfunctieInkomsten",
    rust_name: "PersoonNevenfunctieInkomsten",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOONNEVENFUNCTIEINKOMSTEN_FIELDS,
};

const PERSOONONDERWIJS_FIELDS: &[Field] = &[
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "opleidingNl",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "opleidingEn",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "instelling",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "plaats",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "datumType",
        order: 6,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "datumType",
        order: 7,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 8,
    },
];

const PERSOONONDERWIJS: EntityType = EntityType {
    category: "PersoonOnderwijs",
    xml_element: "persoonOnderwijs",
    rust_name: "PersoonOnderwijs",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOONONDERWIJS_FIELDS,
};

const PERSOONREIS_FIELDS: &[Field] = &[
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "doel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "bestemming",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "van",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "datumType",
        order: 4,
    },
    Field {
        name: "totEnMet",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "datumType",
        order: 5,
    },
    Field {
        name: "betaaldDoor",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "gewicht",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 7,
    },
];

const PERSOONREIS: EntityType = EntityType {
    category: "PersoonReis",
    xml_element: "persoonReis",
    rust_name: "PersoonReis",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: PERSOONREIS_FIELDS,
};

const RESERVERING_FIELDS: &[Field] = &[
    Field {
        name: "activiteit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "zaal",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "statusCode",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "statusNaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "activiteitNummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
];

const RESERVERING: EntityType = EntityType {
    category: "Reservering",
    xml_element: "reservering",
    rust_name: "Reservering",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: RESERVERING_FIELDS,
};

const STEMMING_FIELDS: &[Field] = &[
    Field {
        name: "besluit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieType",
        order: 2,
    },
    Field {
        name: "fractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieType",
        order: 3,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 4,
    },
    Field {
        name: "fractieGrootte",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "unsignedIntType",
        order: 5,
    },
    Field {
        name: "actorNaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "actorFractie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "vergissing",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "booleanType",
        order: 8,
    },
    Field {
        name: "sidActorLid",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
    Field {
        name: "sidActorFractie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 10,
    },
];

const STEMMING: EntityType = EntityType {
    category: "Stemming",
    xml_element: "stemming",
    rust_name: "Stemming",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: STEMMING_FIELDS,
};

const TOEZEGGING_FIELDS: &[Field] = &[
    Field {
        name: "toegezegdAanFractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "toegezegdAanPersoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "isHerhalingVan",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieBijgewerktLiteral",
        order: 3,
    },
    Field {
        name: "isAanvullingOp",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieBijgewerktLiteral",
        order: 4,
    },
    Field {
        name: "isWijzigingVan",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieBijgewerktLiteral",
        order: 5,
    },
    Field {
        name: "aanmaakdatum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateTimeType",
        order: 6,
    },
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "activiteit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 8,
    },
    Field {
        name: "activiteitNummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 9,
    },
    Field {
        name: "naam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 10,
    },
    Field {
        name: "achternaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 11,
    },
    Field {
        name: "initialen",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 12,
    },
    Field {
        name: "tussenvoegsel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 13,
    },
    Field {
        name: "voornaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 14,
    },
    Field {
        name: "achtervoegsel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 15,
    },
    Field {
        name: "titulatuur",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 16,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 17,
    },
    Field {
        name: "status",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "toezeggingstatus",
        order: 18,
    },
    Field {
        name: "datumNakoming",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateTimeType",
        order: 19,
    },
    Field {
        name: "kamerbriefNakoming",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 20,
    },
    Field {
        name: "ministerie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 21,
    },
    Field {
        name: "tekst",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 22,
    },
];

const TOEZEGGING: EntityType = EntityType {
    category: "Toezegging",
    xml_element: "toezegging",
    rust_name: "Toezegging",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: TOEZEGGING_FIELDS,
};

const VERGADERING_FIELDS: &[Field] = &[
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 1,
    },
    Field {
        name: "titel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "zaal",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
    Field {
        name: "vergaderjaar",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "vergaderjaar",
        order: 4,
    },
    Field {
        name: "vergaderingNummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:unsignedInt",
        order: 5,
    },
    Field {
        name: "datum",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 6,
    },
    Field {
        name: "aanvangstijd",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 7,
    },
    Field {
        name: "sluiting",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "xs:dateTime",
        order: 8,
    },
    Field {
        name: "kamer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
];

const VERGADERING: EntityType = EntityType {
    category: "Vergadering",
    xml_element: "vergadering",
    rust_name: "Vergadering",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: VERGADERING_FIELDS,
};

const VERSLAG_FIELDS: &[Field] = &[
    Field {
        name: "vergadering",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 2,
    },
    Field {
        name: "status",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 3,
    },
];

const VERSLAG: EntityType = EntityType {
    category: "Verslag",
    xml_element: "verslag",
    rust_name: "Verslag",
    base: "downloadEntiteitType",
    base_attributes: DOWNLOAD_ENTITEIT_TYPE_ATTRIBUTES,
    fields: VERSLAG_FIELDS,
};

const ZAAK_FIELDS: &[Field] = &[
    Field {
        name: "kamerstukdossier",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "activiteit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "agendapunt",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 3,
    },
    Field {
        name: "gerelateerdVanuit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 4,
    },
    Field {
        name: "vervangenVanuit",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Unbounded,
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 5,
    },
    Field {
        name: "nummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "soort",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "onderwerp",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "stringType",
        order: 8,
    },
    Field {
        name: "gestartOp",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "dateTimeType",
        order: 9,
    },
    Field {
        name: "organisatie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 10,
    },
    Field {
        name: "titel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 11,
    },
    Field {
        name: "citeertitel",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 12,
    },
    Field {
        name: "alias",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 13,
    },
    Field {
        name: "grondslagvoorhang",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 14,
    },
    Field {
        name: "termijn",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "dateTimeType",
        order: 15,
    },
    Field {
        name: "vergaderjaar",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "vergaderjaarType",
        order: 16,
    },
    Field {
        name: "volgnummer",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 17,
    },
    Field {
        name: "status",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 18,
    },
    Field {
        name: "huidigeBehandelstatus",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 19,
    },
    Field {
        name: "afgedaan",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "booleanType",
        order: 20,
    },
    Field {
        name: "grootProject",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "booleanType",
        order: 21,
    },
    Field {
        name: "kabinetsappreciatie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "stringType",
        order: 22,
    },
];

const ZAAK: EntityType = EntityType {
    category: "Zaak",
    xml_element: "zaak",
    rust_name: "Zaak",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: ZAAK_FIELDS,
};

const ZAAKACTOR_FIELDS: &[Field] = &[
    Field {
        name: "zaak",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 1,
    },
    Field {
        name: "persoon",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 2,
    },
    Field {
        name: "fractie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 3,
    },
    Field {
        name: "commissie",
        kind: FieldKind::Relation,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "referentieLiteral",
        order: 4,
    },
    Field {
        name: "actorNaam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 5,
    },
    Field {
        name: "actorFractie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 6,
    },
    Field {
        name: "actorAfkorting",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 7,
    },
    Field {
        name: "functie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 8,
    },
    Field {
        name: "relatie",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 9,
    },
    Field {
        name: "sidActor",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "tokenType",
        order: 10,
    },
];

const ZAAKACTOR: EntityType = EntityType {
    category: "ZaakActor",
    xml_element: "zaakActor",
    rust_name: "ZaakActor",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: ZAAKACTOR_FIELDS,
};

const ZAAL_FIELDS: &[Field] = &[
    Field {
        name: "naam",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: false,
        xsd_type: "tokenType",
        order: 1,
    },
    Field {
        name: "sysCode",
        kind: FieldKind::Attribute,
        min_occurs: 0,
        max_occurs: Occurs::Exactly(1),
        nillable: true,
        xsd_type: "intType",
        order: 2,
    },
];

const ZAAL: EntityType = EntityType {
    category: "Zaal",
    xml_element: "zaal",
    rust_name: "Zaal",
    base: "entiteitType",
    base_attributes: ENTITEIT_TYPE_ATTRIBUTES,
    fields: ZAAL_FIELDS,
};

pub const ENTITY_TYPES: &[EntityType] = &[
    ACTIVITEIT,
    ACTIVITEITACTOR,
    AGENDAPUNT,
    BESLUIT,
    COMMISSIE,
    COMMISSIECONTACTINFORMATIE,
    COMMISSIEZETEL,
    COMMISSIEZETELVASTPERSOON,
    COMMISSIEZETELVASTVACATURE,
    COMMISSIEZETELVERVANGERPERSOON,
    COMMISSIEZETELVERVANGERVACATURE,
    DOCUMENT,
    DOCUMENTACTOR,
    DOCUMENTVERSIE,
    FRACTIE,
    FRACTIEZETEL,
    FRACTIEZETELPERSOON,
    FRACTIEZETELVACATURE,
    KAMERSTUKDOSSIER,
    PERSOON,
    PERSOONCONTACTINFORMATIE,
    PERSOONGESCHENK,
    PERSOONLOOPBAAN,
    PERSOONNEVENFUNCTIE,
    PERSOONNEVENFUNCTIEINKOMSTEN,
    PERSOONONDERWIJS,
    PERSOONREIS,
    RESERVERING,
    STEMMING,
    TOEZEGGING,
    VERGADERING,
    VERSLAG,
    ZAAK,
    ZAAKACTOR,
    ZAAL,
];
